- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

  - name: Create a change request
    snow_record:
      state: present
      table: change_request
      username: admin
      password: fC84GfsdHHQe
      instance: dev65227
      data:
        severity: 2
        priority: 2
        short_description: "This is a test opened by Ansible"
    register: new_incident

  - debug: 
      var: new_incident.record.number